datastore.go

fixes two occurrences of the word "interpreted" in datastore.go

Fixes typo in datastore.go

---

limitedstore/limitedstore.go

This fix is in limitedstore/limitedstore.go, to intelligently terminate existing file uploads. The ```store.uploads``` map is sorted, and then analysed to remove the bigger existing uploads first. 
The extraneous Pair and Pairlist structures are created in order to sort the map by values. Sorry for the indentation issues, surprisingly they didn't sync.

Sorting before termination of uploads in limitedstore.go

---

cmd/tusd/main.go

If you are working behind a load balancer the load balancer might handle this and send an EOF.  In that case, you want to have no read and write timeouts at all, so we should support the 0 setting as "unlimited" just like the Connection itself.

Support 0 as a "no timeout" setting

---

cmd/tusd/cli/composer.go
cmd/tusd/cli/flags.go

How to test:
Download and run [minio](https://github.com/minio/minio) : ./minio server /tmp/minio-test-files
Go to http://127.0.0.1:9000 (minio web UI) and create a bucket with name "test"
Set AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY and AWS_REGION from output of minio.
Run : go run cmd/tusd/main.go -s3-bucket test -s3-endpoint http://127.0.0.1:9000.
Run tus-js-client demo and set upload endpoit to http://localhost:1080/files/ and chunk size to 5242880 bytes(5MB).
Upload some files to test.
Refresh minio web UI.
This maybe work with new version of Ceph(Kraken) but not with Jewel because of an old version of embedded web server(civetweb) that doesn't support absolute URI.

Add -s3-endpoint to command line arguments to support S3 compatilbe implementations like minio

---

Dockerfile

This Dockerfile works quite nicely and produces an image of only 256 MB. 
Docker entrypoint is configured to make use of the dirs /srv/tusd-data and /srv/tusd-hooks. You can therefore mount an outside dir with your private hooks onto /srv/tusd-hooks and tusd will automatically use them. 
As the image is using ENTRYPOINT for the basic start command, it is possible to provide additional startup args to tusd by adding them to `docker run` after the image name:
`docker run --name tusd -it -v $PWD/tusd-data/:/srv/tusd-data/ -v $PWD/tusd-hooks/:/srv/tusd-hooks -e AWS_REGION=eu-central-1 flaneurtv/tusd -s3-bucket tusd-bucket -s3-endpoint https://s3.eu-central-1.amazonaws.com`
The Dockerfile should work for both, local builds as well as Docker Hub automatic builds. However, judging from the way …

working alpine Dockerfile usable for local and autobuild

---

gcsstore/gcsservice.go
gcsstore/gcsstore.go
gcsstore/gcsstore_test.go

- This affects the GCSStore only.
Before:
The GCSStore did not search for the proper prefix, which meant that composed files were not seen and always returned 0 for `Upload-Offset` for completed uploads.
Now:
GCSStore checks for all files matching the hash, including completed files and the info file. 
Specifics: 
Before, when an object was composed and finished uploading, it took the filename of `<RANDOM_HASH>`, while tusd used the prefix of `<RANDOM_HASH>_`, resulting in it not finding any files, and stating the uploaded file did not exist, resulting in an `Upload-Offset` of `0`. This PR now checks the bucket for all files with the prefix of `<RANDOM_HASH>`, which now accounts for composed files. 
cc:
@devonbalicki @vayam

GetInfo now properly retrieves info for composed objects

---

cmd/tusd/cli/hooks.go
cmd/tusd/cli/log.go

Hooks currently get logged into stderr, which (if you're running tus in GKE) result in hook logs being erroneously reported as errors. This PR sets hook logs to go to stdout. 
It's also possible that this should be a user configurable setting, I'm open to suggestions on how this should be implemented.

Log hooks to stdout

---

gcsstore/gcsservice.go
gcsstore/gcsstore.go
gcsstore/gcsstore_test.go

This makes the Google Cloud Storage store consistent with the S3 store implementation by making `GetInfo` return `ErrNotFound` when the object is not found.
This also makes the HEAD request return `404` instead of `500` when attempting to get the upload status of a non-existent file stored on GCS.

Handle GCS object not found error

---

cors_test.go
unrouted_handler.go

This is a followup to #182 that adds the `Upload-Defer-Length` header to the `Access-Control-{Allow,Expose}-Headers` lists and addresses feedback from the earlier PR.
cc @Acconut @kvz

Add CORS support for Upload-Defer-Length header

---

cmd/tusd/cli/composer.go

Previously, you could _only_ use environment variables.   This change enables the SDK to handle credentials according to its standard "credential chain".  Per the [docs](https://github.com/aws/aws-sdk-go#configuring-credentials):
> By default the SDK will source credentials automatically from its default credential chain. See the session package for more information on this chain, and how to configure it. The common items in the credential chain are the following:
> * Environment Credentials - Set of environment variables that are useful when sub processes are created for specific roles.
> * Shared Credentials file (~/.aws/credentials) - This file stores your credentials based on a profile name and is useful for local development.
> * EC2 Instance Role Credentials - Use EC2 Instance Role …

Allow AWS-SDK to handle gathering credentials

---

unrouted_handler.go

There is currently an issue wherein PATCH-ing a file which had `Upload-Defer-Length` with `Upload-Length` only results in error. I believe it's the case that the `uploadLength` is checked against the `MaxSize` in the handler, which by default is `0.00` (i.e. no limit). This should cover the default case.

Updates uploadLength logic in PatchFile

---

docs/hooks.md

HTTP Status Code meaning was missed.
Source code reference: https://github.com/tus/tusd/blob/311cdf253e50a21b12c0cae094ed0c2d20c66d5c/cmd/tusd/cli/hooks.go#L137

Add documentation about HTTP Hooks status code

---

gcsstore/gcsservice.go
gcsstore/gcsservice_test.go
gcsstore/gcsstore.go
gcsstore/gcsstore_mock_test.go
gcsstore/gcsstore_test.go

In production on Vimeo we were seeing an issue where requests to calculate the current offset of an upload were taking an incredibly long time. We discovered that this was only happening for uploads that had a large number of composable parts. A head request to a file with >200 parts was taking over a minute to respond. 
In order to speed this process up, this PR changes the `GetObjectSize` calls in the store's `GetInfo` method to run concurrently. We limit this concurrency with a semaphore that allows at most 32 goroutines to be working on this task at a time. 
This performance improvement required that we pass context to `GCSService` rather than using an internal and shared one. The reason being that if one `GetObjectSize` call in a goroutine fails, we need a way to cancel all …

Add support for concurrent GetObjectSize requests

---

.scripts/test_all.sh
etcd3locker/lock.go
etcd3locker/locker.go
etcd3locker/locker_options.go
etcd3locker/locker_test.go
vendor/vendor.json

Resolves: https://github.com/tus/tusd/issues/157
This is a first pass at an etcd3 locker that uses the built-in locks (from the `etcd/clientv3/concurrency` package). We create sessions with valid leases to lock an upload. Sessions are created with a renewing 60s lease (but kept alive with KeepAlive as long as the process is still alive). These sessions are reused to unlock uploads when the upload completes. Once an upload has been unlocked, we close the session. 
This code has been tested locally with an install of `etcd3` (3.1, 3.2, 3.3) with the use of the `go-etcd-harness`. 
We're also running this locker with some small scale traffic to our tusd server, in which we haven't seen issues so far. 
Example Usage (pseudocode):
```
import (
"fmt"
"time"
"github.com/coreos/etcd/clientv3" …
```

etcd3 Locker: First pass

---

cors_test.go
unrouted_handler.go

Added Upload-Concat to Access-Control-Allow-Headers for enabling browsers to make use of the concatenation extension, this fixes the following issue: #214

Added Upload-Concat to Access-Control-Allow-Headers

---

README.md
etcd3locker/lock.go
etcd3locker/locker.go
etcd3locker/locker_options.go

I saw that godoc didn't render my documentation within the code very well so I fixed up the formatting in the hopes that things look better now.
In addition, I saw various instances of `timeout` and `ttl` when it should be `ttl` so I did a quick correction of places that had `sessionTimeout` / `timeout` to make it all consistent.

etcd3locker: Update formatting of docs; timeout -> ttl substitution

---

cmd/tusd/cli/composer.go
cmd/tusd/cli/flags.go
s3store/s3store.go
s3store/s3store_test.go

Currently, all objects in S3 are placed in the root of the bucket. This makes tusd adoption difficult for existing applications that use a different convention, such as using S3's support for prefixes to place objects in a pseudo-directory like `s3://my_bucket/media/incoming/<upload id>`. This PR introduces an `ObjectPrefix` field on `S3Store` to enable the use of prefixes.
Addresses one of the requests in #207.

Support prefix on S3 object names

---

Dockerfile

This makes it easier to reason about tusd's run environment. It also
significantly lowers the docker image size from 280MB for the current 0.11.0
image to only 26MB. Also not having the entire build environment in the
shipped images makes it quite attractive to use this image as a base
for other images. Those could contain some custom hooks for example.

refactor(image): switch to a multistage build for the container image

---

s3store/s3store.go
s3store/s3store_mock_test.go
s3store/s3store_test.go
s3store/s3store_util_test.go

Currently, the S3 backend will drop non-final parts that are smaller than `MinPartSize` to comply with constraints in the AWS S3 service. This is inefficient, and it also prevents S3Store from supporting the `creation-defer-length` extension.
This PR implements an idea that was proposed in #182: when a part is smaller than `MinPartSize`, we send it to S3 temporarily as a normal (non-multipart upload) object. On the next `PATCH` request for the upload, the temporary part is retrieved from S3 and prepended to the request body. This process may be repeated until the part is large enough to be added to the multipart upload.

S3Store: Add support for creation-defer-length extension

---

s3store/s3store.go
s3store/s3store_test.go

A case that isn't covered by #219 is when the `HeadObject` call to the S3 endpoint returns `NotFound` instead of `NoSuchKey` or `AccessDenied`. Depending on the permissions granted to the request, any of these errors may be returned.
This also accommodates third party implementations of the S3 interface, such as Minio, whose behavior may differ slightly from S3's.
Resolves #226.

Handle "NotFound" error code from HeadObject

---

.travis.yml

The new Docker instructions require a newer version than is installed on Travis CI by default.

Install new Docker version on CI

---

consullocker/consullocker.go
etcd3locker/locker.go

The following statement in the docs is not accurate for consullocker and etcd3locker. 
> If no such lock exists, no error will be returned. 
This PR removes that statement for both locker implementations.

Docs: consullocker/etcd3locker - correct UnlockUpload method docs

---

cmd/tusd/cli/hooks.go
docs/hooks.md
unrouted_handler.go

Forward status code and body from Pre-create http hook

---

s3store/s3store.go
s3store/s3store_mock_test.go
s3store/s3store_test.go

This is a followup from #219 and addresses two issues related to IAM permissions. 
First, the use of `HeadObject` as an optimization requires the `s3:ListBucket` permission to be granted, and using both `HeadObject` and `GetObject` to reference .part files was difficult to reason about. This is resolved by using `GetObject` only. ~Second, buckets that are configured with object versioning would have needed the `s3:DeleteObject` and `s3:DeleteObjectVersion` permissions to be granted, which is not ideal and represents a breaking change. By overwriting the existing .part object (if any) with an empty one, we can avoid the complexity associated with deleting objects.~ (See comments below.)
See #226 for more discussion.

S3Store: IAM fixes for incomplete parts

---

.hooks/post-create
.hooks/post-finish
.hooks/post-receive
.hooks/post-terminate
.hooks/pre-create
Dockerfile

Hi,
this PR is to fix #203. It does:
Update Dockerfile to install the small jq package to parse the JSON data.
Update all the sample hook files to replace "bash" with "sh"
as bash is not installed by default in Alpine linux
and we don't want to install it as it's not a lightweight package.
The container size before this PR: 26.7MB
The container sizse after this PR:  27.7MB
Kind regards
Rija

Enable the sample hook files to execute without error to fix #203

---

README.md

Closes #258. 
This PR adds a link to the `tusd-dynamo-locker` in the README.

Add tusd-dynamo-locker link to README.md

---

cmd/tusd/cli/flags.go
cmd/tusd/cli/listener.go
cmd/tusd/cli/serve.go

As suggested in tus/tusd#264, this PR brings the ability for `tusd` to bind to a UNIX socket.
The implementation adds a `-unix-sock` CLI option which if set to a non-empty value will bind `tusd` to the provided path and discard the TCP host and port.
I'm unsure about the standards of the project, so please me how I can improve this.

Create CLI option to bind to UNIX socket

---

config.go

This PR adds timestamps to tusd logger. 
The following line is modified https://github.com/tus/tusd/blob/master/config.go#L50 by setting the timestamp flags to the Log config
```go
if config.Logger == nil {
config.Logger = log.New(os.Stdout, "[tusd] ", log.Ldate | log.Lmicroseconds)
}
```
Flags log.Ldate | log.Lmicroseconds are used producing this kind of log line
```
[tusd] 2019/05/24 11:39:18.827952 event="RequestIncoming" method="HEAD" path="..."
```
Closes #274

Add timestamps to tusd log 

---

cmd/tusd/cli/metrics.go

I was not able to build the docker container unless doing the changes contained in this pr. Is it correct? Has the handler been in another package before?

adopted change in prometheus client lib.

---

Dockerfile

User tusd has been created but is not selected for the tusd process within the container. Fixed in this Dockerfile.

Set the docker user to tusd.

---

Dockerfile

This fixes the issues with the docker build process.

Installing gcc and libc-dev for having a matching gcc and linker in the image.

---

Dockerfile

Updated the base image to use the current alpine version which is supported until 2020-11-01 (https://wiki.alpinelinux.org/wiki/Alpine_Linux:Releases)

Updated docker from alpine 3.8 to 3.9

---

.scripts/generate-docker-library.sh
generate-docker-library.sh

As promised, here is the generator-script to create a new official-images tusd file. It automatically builds docker tags based on git tags and starts with version 0.13.1. Created and tested on macOS.

Added script to generate official-images/library/tusd file.

---

s3store/s3store.go

Hi :)
When s3store is used in the os temp folder there are `tusd-s3-tmp*` files accumulating space.
The problem was in the WriteChunk method incompletePartFile must close it before remove it.
This was fixed in one line :)

[FIX] s3store residual temp files

---

README.md

Tiny updated to README to fix typos and current parameter names at `tus -help` output.

Make README file represent current reality

---

pkg/gcsstore/gcsservice.go
pkg/handler/cors_test.go
pkg/handler/utils_test.go

This PR:
- Replaces deprecated GCS [WithServiceAccountFile](https://godoc.org/google.golang.org/api/option#WithServiceAccountFile) with [WithCredentialsFile](https://godoc.org/google.golang.org/api/option#WithCredentialsFile).
- Replaces deprecated [ResponseRecorder HeaderMap](https://golang.org/pkg/net/http/httptest/#ResponseRecorder) with [Header()](https://golang.org/pkg/net/http/httptest/#ResponseRecorder.Header).
- Fixes some typos.

Update deprecated methods

---

pkg/filestore/filestore.go

Since the `file` is not used after the creation, its closing can be done without defer (and the err can be checked).

filestore.NewUpload: Remove useless defer

---

pkg/s3store/s3store.go
pkg/s3store/s3store_test.go

As discussed in #336, this is a simpler approach to support automatic cleanup of metadata objects.
tusd's temporary metadata objects (.info, .part, etc) can become a maintenance burden for certain applications. For example, applications may place uploaded objects directly into their final bucket in order to avoid slow copy operations. However, this means that the metadata objects are also placed in the same bucket. This can confuse automated tools and creates a nontrivial amount of cruft in the bucket over time.
This PR introduces a `MetadataObjectPrefix` field that, when set, will be applied instead of `ObjectPrefix` for .info and .part objects. By providing a separate object prefix, tusd operators can define an [S3 object lifecycle …

S3Store: Add optional key prefix for metadata objects

---

cmd/tusd/cli/hooks/grpc.go
cmd/tusd/cli/hooks/proto/v1/hook.proto

Make use of gRPC metadatas to pass on Hook-Name.

---

docs/hooks.md

Headers in Go are `map[string][]string` but the docs show them as being single values.
Also minor update to mention that `Storage` is null in the pre-create hook.

docs: Headers are a list of values

---

cmd/tusd/cli/flags.go
cmd/tusd/cli/hooks.go
cmd/tusd/cli/hooks/http.go
docs/hooks.md

cli: add header forwarding in HTTP hooks

---

examples/nginx.conf
pkg/handler/head_test.go
pkg/handler/post_test.go
pkg/handler/unrouted_handler.go
pkg/handler/unrouted_handler_test.go
pkg/s3store/s3store.go
pkg/s3store/s3store_part_producer_test.go
pkg/s3store/s3store_test.go

As discussed in #379, the throughput performance of S3Store can degrade when the S3 (or compatible) API has high or unpredictable latency. Currently, S3Store synchronously reads bytes from the client, writes them to disk, and then writes the file on disk to the S3 API. That approach is simple and reliable, but it blocks the client from transmitting any new bytes while tusd is writing the current part to S3. This blocking causes the client to transmit more slowly due to standard TCP behavior.
This PR introduces `s3ChunkProducer`, a struct that is responsible for consuming bytes from the source reader (connected to the client) and converting them into `*os.File` instances that are pushed into a channel. The original request goroutine then consumes files from this channel until it's empty …

S3Store: Concurrently write upload parts to S3 while reading from client

---

cmd/tusd/cli/composer.go
cmd/tusd/cli/flags.go
pkg/s3store/calcpartsize_test.go
pkg/s3store/s3store.go
pkg/s3store/s3store_test.go

This PR introduces a PreferredPartSize property to the S3Store which controls how big tusd should make the individual parts. The goal is to reduce the number of HTTP requests that must be made to AWS S3 (or S3 compatible storages). 
With these changes the default part size would be increased from 5MB (the minimum part size) to 50MB. I chose this number arbitrary and I want to compare upload performance for different part sizes in order to determine the best default value.
The PR also adds a new flag `-s3-part-size` to control the part size for easier benchmarking and performance tuning.
~~The tests are not yet adjusted to these changes, but I will take care of them.~~
/cc @acj

s3store: Increase default part size

---

cmd/tusd/cli/flags.go
cmd/tusd/cli/serve.go
docs/faq.md
docs/usage-binary.md

* Adds `-tls-certificate`, `-tls-key`, and `-tls-mode` flags
* Alter printed URL to reflect protocol in use
* For non-TLS, do an eary-exit if http.Serve() returns
* Configure TLS for the following modes
* TLSv1.3-only
* (default) TLSv1.3+TLSv1.2, with recommended ciphersuites from Mozilla
* TLSv1.2 only, with only 256-bit AES ciphersuites
* All modes disable HTTP/2, given that it’s not supported in non-TLS mode
* Update documentation
Resolves #418

Add TLS support to tusd

---

go.sum
pkg/handler/post_test.go
pkg/handler/unrouted_handler.go
pkg/handler/unrouted_handler_test.go

should use `;` instead of `,` in https://github.com/tus/tusd/blob/f863189009bb9e8a279c7d2a11f3b7503e3a9c7e/pkg/handler/unrouted_handler.go#L24
which causes the returned `host` (when `handler.config.RespectForwardedHeaders` is set to `true`) https://github.com/tus/tusd/blob/f863189009bb9e8a279c7d2a11f3b7503e3a9c7e/pkg/handler/unrouted_handler.go#L1032 to be `upload.example.tld;proto=https;proto-version=` instead of `upload.example.tld`.

Fix unrouted handler forwarded header

---

pkg/s3store/s3store.go
pkg/s3store/s3store_test.go

Fixes #396, which has a rich discussion of the bug. There is a subtle interaction between UnroutedHandler and S3Store when using deferred length. The result is that the last chunk of an upload, if it's less than 5MB, is ignored.

S3Store: Fix data inconsistency bug when using Upload-Defer-Length

---

scripts/build_all.sh

Add arm64 binaries for linux.
https://github.com/tus/tusd/pull/458 adds arm64 binaries for darwin (macOS)

Compile tusd for arm64

---

cmd/tusd/cli/log.go

Currently log config is writing timestamp with second  precision but usually this is not enough to correctly track the requests. 
This PR proposes to use the microsecond precision for the logging timestamps. 
Loking at the standar log package (https://golang.org/pkg/log/#pkg-constants), there is no alternative to the microsecond precision.

Change timestamp to microseconds precision in log

---

.github/workflows/continuous-integration.yaml

When using a Windows runner, it does not catch the first exit code that comes from when running `go test ./...`, and since `go vet ./...` exits with a non-zero exit code. The step succeeds correctly.
So this PR just moves `go vet ./...` to its separate step

ci: fix non-failing windows test when it should fail

---

pkg/s3store/s3store.go

What's up: some upload-metadata values will be successfully delivered (thanks to b64encode) but then cause an error communicating with S3.
How to reproduce:
```
$ curl -X POST -H 'Upload-Metadata: filename dGVzdC5/Lm1wNA==' [...]
[...]
500 Internal Server Error: s3store: unable to create multipart upload:
RequestError: send request failed
caused by: Post "https://s3.example.net/tusd/d167476518c4ac7e01d3a9bd7beaa0ce?uploads=": net/http: invalid header field value "test.\u007f.mp4" for key X-Amz-Meta-Filename
```
Tracing back lead us here https://cs.opensource.google/go/go/+/master:src/net/http/transport.go;l=528
then here https://pkg.go.dev/golang.org/x/net/http/httpguts#ValidHeaderFieldValue
and eventually refers to a few HTTP RFCs.
From `net/http` implementation (as well as from the …

s3store: stricter character replacement regexp for x-amz-metadata

---

.github/dependabot.yaml

I see you also suffer from daily dependabot updates regarding AWS SDK, which they release a new version daily. They do the same in their python SDK, so we've adjusted it down to weekly checks instead of daily.
That way we still get dependabot updates, but not spammed down with it.

fix: set dependabot to check weekly instead of daily

---

pkg/handler/unrouted_handler.go

Some implementations make a `PATCH` request to inform the server about the upload size after the last byte is sent:
```javascript
// tus-js-client/lib/upload.js
// ...
// If the upload length is deferred, the upload size was not specified during
// upload creation. So, if the file reader is done reading, we know the total
// upload size and can tell the tus server.
if (this.options.uploadLengthDeferred && done) {
this._size = this._offset + (value && value.size ? value.size : 0)
req.setHeader('Upload-Length', this._size)
}
if (value === null) {
return this._sendRequest(req)
}
this._emitProgress(this._offset, this._size)
return this._sendRequest(req, value)
// ...
```
This PR simply adds a check to `PatchFile` so that `writeChunk` isn't called if there are no bytes to write.

fix: avoiding `writeChunk` no-op

---

pkg/handler/unrouted_handler.go

fixed typo to allow video/ogg content-disposition inline.
fixed comment typos.
In an offline branch I also added 'video/mp4' to be served inline, but I know the MP4 container supports more video+audio codecs than browsers are capable of displaying.  Would it be possible to add whitelisted codecs?
such as:
'video/mp4; codecs="avc1.4d002a"'
https://developer.mozilla.org/en-US/docs/Web/Media/Formats/codecs_parameter#general_syntax

fix mimeInlineBrowserWhitelist typo

---

pkg/s3store/s3store.go

Fixes: #456 
Add the store prefix to the sources when calling concatUsingMultipart. This fixes the bug mentioned in the above PR which was being triggered whenever a parallel upload with parts > 5MB was being concatenated.

Add prefix to parallel upload concat source

---

pkg/handler/config.go

It is useful to correctly track the requests if log of events other than hooks are written timestamps with microseconds.

Change timestamp to microseconds in log

---

.gitignore
Dockerfile
docker/entrypoint.sh
docker/load-env.sh
docs/faq.md
examples/docker-compose.yml

This pull request resolves the requested feature #799 to read mounted Docker Secrets from /run/secrets folder into corresponding ENV vars. The ENV vars are defined inside **docker/load-env.sh** script. If a _FILE suffix is added to an ENV var, the script tries to read the corresponding file and sets the environment variable without _FILE suffix to the same value.

Docker: add docker secret env parsing

---

cmd/tusd/cli/hooks/grpc.go

This pull request allows the HTTPRequest headers to be passed from the clients to the gRPC hook. From each HTTPRequest header element, the first value is passed to the hook.

Pass HTTPRequest header to gRPC Hook

---

pkg/filestore/filestore.go

`info.ID` could be set external e.g. by `config.PreUploadCreateCallback`
is already set in
- s3store (complicated)
- gcsstore (get from there)
- azurestore (get from there)

filestore: keep ID passed to NewUpload, if available

---

.github/workflows/release.yaml

Newer Mac computers with their M1 chips use the ARM architecture [1]. Currently there is no docker image for postgraphile published to Docker Hub supporting the `arm64` platform, only for `amd64`. This commit adds compilation for an ARM image as well, so that developers on newer Mac computers can use postgraphile inside a container as well.
[1] https://en.wikipedia.org/wiki/Apple_M1
The build time will be longer. Especially cross-platform compilation for ARM will take longer than AMD compilation on AMD ci workers due to necessary QEMU virtualization.
I chose `fix` as the type, as it does not really add a new feature to tusd but adds a missing platform for Mac.

fix(ci): build arm64

---

docs/usage-binary.md

Adds documentation for using the Azure Blob Storage backend, as requested in issue #897

Add usage docs for using azure storage backend

---

.github/workflows/continuous-integration.yaml
.github/workflows/release.yaml

Provided by https://github.com/actions/setup-go/releases/tag/v3.5.0

ci: Automatically use latest Go versions

---

cmd/tusd/cli/flags.go
cmd/tusd/cli/serve.go
docs/usage-binary.md
pkg/handler/body_reader.go
pkg/handler/patch_test.go
pkg/handler/unrouted_handler.go

This PR implements a graceful shutdown for tusd. Once it receives a shutdown instruction, it will stop listening and try to close down all uploads properly, so that data stores and locker can properly clean up. It waits for a specific period after the first shutdown instructions. If the requests are not all closed down at this point, it will exit regardless.
Closes #395 
Tasks:

Graceful shutdown

---

pkg/handler/config.go
pkg/handler/context.go
pkg/handler/context_test.go
pkg/handler/datastore.go
pkg/handler/hooks.go
pkg/handler/unrouted_handler.go
pkg/handler/utils_test.go

Closes #713, https://github.com/tus/tusd/issues/443, https://github.com/tus/tusd/pull/455, https://github.com/tus/tusd/pull/315, https://github.com/tus/tusd/pull/740, https://github.com/tus/tusd/pull/342
Hooks and data stores are given access to the request context, but in a slightly modified way:
```
// Context provides access to the context from the HTTP request. This context is
// not the exact value as the request context from http.Request.Context() but
// a similar context that retains the same values as the request context. In
// addition, Context will be cancelled after a short delay when the request context
// is done. This delay is controlled by Config.GracefulRequestCompletionDuration.
//
// The reason is that we want stores to be able to continue processing a request after
// …
```

Provide values from request context to store

---

pkg/s3store/s3store.go

Referring to this issue: https://github.com/tus/tusd/issues/1010

Add additional s3 error to ignore when file doesn't exist.

---

pkg/handler/config.go
pkg/handler/cors_test.go
pkg/handler/head_test.go
pkg/handler/patch_test.go
pkg/handler/post_test.go
pkg/handler/unrouted_handler.go

There are two breaking changes that we need to incorporate: Upload-Complete and the new interop version. See https://www.ietf.org/archive/id/draft-ietf-httpbis-resumable-upload-02.html#name-since-draft-ietf-httpbis-re

Update to RUFH draft 02

---

docs/hooks.md

Update CLI option examples from 2 leading dashes to just 1.

docs: Unify style of CLI arguments

---

pkg/s3store/s3store.go

When downloading a completed upload via a GET request from DigitalOcean Spaces, an error would be returned because the corresponding multipart uploads was (as expected) not found. This PR patches the error handling to correctly ignore this error.
Fixes an error discovered in https://github.com/tus/tusd/issues/1067#issuecomment-1907924262.
See https://github.com/tus/tusd/issues/1015 for similar errors in the past.

s3store: Fix downloads from some S3-compatible stores

---

docs/hooks.md
pkg/handler/unrouted_handler.go

These restrictions are included to ensure that upload IDs fit well into a URI's path and that we can always extract the same exact upload ID as was encoded in the URL.
Closes #1030.

handler: Valid upload IDs from pre-create hooks

---

pkg/azurestore/azurestore.go
pkg/azurestore/azurestore_test.go

Closes https://github.com/tus/tusd/issues/1031
Instructions for testing this out locally:
1. `npm install -g azurite`
2. `brew install azure-cli` or similar depending on OS
3. Start Azurite: `azurite --location ./azurite/ --debug ./azurite/debug.log`
4. Create container: `az storage container create --name mycontainer --connection-string "DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;"`
5. Start tusd: `AZURE_STORAGE_ACCOUNT=devstoreaccount1 AZURE_STORAGE_KEY=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw== go run cmd/tusd/main.go -azure-endpoint http://127.0.0.1:10000/devstoreaccount1 …

azurestore: Buffer upload data on disk instead of in-memory

---

pkg/handler/head_test.go
pkg/handler/patch_test.go
pkg/handler/post_test.go
pkg/handler/unrouted_handler.go
pkg/handler/utils_test.go

This PR adds support for the [new draft version](https://datatracker.ietf.org/doc/html/draft-ietf-httpbis-resumable-upload-03). It does not include major changes beside allowing a new response code for HEAD requests (which we don't use) and an increment in the interoperability version.
This PR preserves the support for earlier draft versions.

handler: Support RUFH draft -03

---

pkg/handler/body_reader.go
pkg/handler/unrouted_handler.go

Currently, if a RUFH PATCH requests gets interrupted, the error is swallowed by the bodyReader. This is not a problem for tus uploads, but leads to issues with RUFH uploads because a successful RUFH PATCH request with Upload-Complete: ?1 will set the upload length. If an interrupted PATCH is thus interpreted as successful, it will cause the upload length to be set to the offset at which the upload was interrupted and thus preventing the upload from being resumed.
This PR fixes this problem by not swallowing the error, making the handler aware of the interruption.

handler: Fix error with RUFH upload ending too soon

---

pkg/filestore/filestore.go

In the current logic, we first delete the bin file and then the info file. We should instead do the reverse and ignore any errors when deleting the bin file. This ensures that any disgraceful shutdown would properly recover.
*Note:* This is only fixed in the filestore for now - might need to fix for other stores as well.

Fix graceful terminate in filestore.

---

pkg/s3store/s3store.go
pkg/s3store/s3store_test.go

To be compatible with object id that contains `+` .

s3store: Allow `+` in object IDs

---

pkg/gcsstore/gcsservice.go
pkg/gcsstore/gcsstore.go
pkg/gcsstore/gcsstore_test.go

Change r.Read(buf) to io.ReadFull(buf) as discussed in issue #1124 to fix EOF error on .info read from GCS

gcsstore: Fix error creating new uploads

---

pkg/filelocker/filelocker.go
pkg/filelocker/filelocker_test.go

Fixes https://github.com/tus/tusd/issues/1148

filelocker: Emit 404 if directory for lock does not exist

---

docs/_advanced-topics/hooks.md
pkg/filestore/filestore.go
pkg/filestore/filestore_test.go

This PR includes two changes:
- When the `pre-create` hooks specifies an absolute path where the blob file should be stored, the absolute path was wrongfully joined to the storage directory and treated as relative. This PR fixes this.
- The location of the `.info` file is no exposed to hooks as `Storage.InfoPath`.

filestore: Expose `.info` path and fix absolute paths

---

pkg/handler/concat_test.go
pkg/handler/unrouted_handler.go

Fixes https://github.com/tus/tusd/issues/1169.

handler: Emit pre-finish hook for concatenated uploads

---

cmd/tusd/cli/flags.go
cmd/tusd/cli/hooks.go
pkg/hooks/grpc/grpc.go

This adds the `-hooks-grpc-forward-headers` option to forward a list of selected header fields from the request to tusd to the gRPC request to the gRPC server. Can be useful for passing through Authorization headers.
Closes https://github.com/tus/tusd/issues/1112.

hooks: Add option to forward HTTP header to gRPC requests

---

pkg/handler/patch_test.go
pkg/handler/unrouted_handler.go

A datastore may wrap errors with additional information. Before the fix, the error was converted to the InternalServerError type by the handler.

handler: unwrap errors using `errors.As`

---

pkg/handler/head_test.go
pkg/handler/options_test.go
pkg/handler/patch_test.go
pkg/handler/post_test.go
pkg/handler/unrouted_handler.go
pkg/handler/utils_test.go

Support for [-04](https://datatracker.ietf.org/doc/draft-ietf-httpbis-resumable-upload/04/) and [-05](https://datatracker.ietf.org/doc/draft-ietf-httpbis-resumable-upload/05/). All changes can be seen in https://www.ietf.org/archive/id/draft-ietf-httpbis-resumable-upload-05.html#name-changes, but the relevant changes for tusd are:

handler: Support IETF draft -04 and -05

---

pkg/filestore/filestore.go

This PR fixes a bug where if the bin file was deleted without errors in the filestore, the `.info` file would not be deleted.
The main issue is that the `!errors.Is(err, os.ErrNotExist)` check is being made without checking that `err` is actually not `nil`. The `nil` value will pass this `if` case and the subsequent cleanup of `.info` file will not happen in that case because the function returns at that point.
I checked the fix in my setup and now it actually removes the `.info` file as well.

filestore: Fix `.info` file not deleted if the binary file was successfully deleted

---

docs/_storage-backends/aws-s3.md
pkg/s3store/s3store.go
pkg/s3store/s3store_test.go

After this PR, if the client passes a `contentType` value in the `metadata` object, the resulting file on S3 will be created with the value passed.
This change causes tusd for Go to match the NodeJS version's behavior, discussed here: https://stackoverflow.com/questions/74148196/how-to-resolve-application-octet-stream-in-s3-using-tus-node-tusd-uppy-or-net.

s3store: Pass Content-Type from `filetype` metadata field to S3

---

cmd/tusd/cli/composer.go
docs/_storage-backends/google-cloud-storage.md
pkg/gcsstore/gcsservice.go

When deploying tusd under GCP, it is better to use integrated Application Default Credentials discovery mechanism, that exists under most google SDK's.
This change simply allows _not_ providing any string as credential file, and then client library defaults to trying ADC as per https://cloud.google.com/docs/authentication/application-default-credentials 
If this proposal is acceptable, I could update the readme as well.

cli: Allow Application Default Credentials discovery for GCP

---

cmd/tusd/cli/composer.go
cmd/tusd/cli/flags.go
cmd/tusd/cli/hooks.go
cmd/tusd/cli/log.go
cmd/tusd/cli/metrics.go
cmd/tusd/cli/serve.go

This enables the user to enable or disable the startup logs while starting the tusd server. It helps the user suppress the startup logs as per their preference.
The flag has a default value of true.
Fixes #1216.
Before:
<hr/>
After:
**set as false:**
**set as true explicity:**
**default:**

cli: Add `show-startup-logs` flag to reduce startup log verbosity

---

go.mod
go.sum
pkg/handler/unrouted_handler.go

This allows the logger passed to the tusd handler to access the request specific context and pull out things like sentry information or trace information. Implements #1236

handler: Pass request context to logger when logging

---

pkg/filestore/filestore.go

Provided one solution to [issue #1238](https://github.com/tus/tusd/issues/1238)

filestore: Close files correctly when concatenating uploads

---

.github/workflows/release.yaml

Latest Ubuntu images don't include the Heroku CLI anymore, causing deployments to fail.
See https://github.com/AkhileshNS/heroku-deploy/issues/188

ci: Install missing Heroku CLI

---

pkg/handler/get_test.go
pkg/handler/unrouted_handler.go
pkg/handler/unrouted_handler_test.go

This pull request includes several changes to the `pkg/handler` package, focusing on improving the handling of MIME types and adding new tests. The most important changes include fixing a regular expression, updating comments, modifying the MIME type whitelist, and adding new unit tests.
Improvements to MIME type handling:
* [`pkg/handler/unrouted_handler.go`](diffhunk://#diff-470f9eeff1025160ca44d324fc316e0ed2ebeb9da748e43c9dd30dfafe01d132L37-R37): Fixed a regular expression in `reMimeType` to correctly match MIME types with a plus sign.
* [`pkg/handler/unrouted_handler.go`](diffhunk://#diff-470f9eeff1025160ca44d324fc316e0ed2ebeb9da748e43c9dd30dfafe01d132L1115-R1117): Updated comments to correct typos and improve clarity.
* [`pkg/handler/unrouted_handler.go`](diffhunk://#diff-470f9eeff102 …

handler: Allow media type parameters in Content-Type headers

---

pkg/azurestore/azureservice.go

azurestore: Fix the GetOffset to work with enabled Azure blob versioning

azurestore: Fix the GetOffset to work with enabled Azure blob versioning

---

cmd/tusd/cli/flags.go
cmd/tusd/cli/hooks.go
docs/_advanced-topics/hooks.md
examples/hooks/http/server.py
internal/e2e/e2e_test.go
pkg/hooks/http/http.go

This PR enhances the HTTP Hooks functionality by introducing several improvements as discussed in issue #1273.
It implements the following:
- **`-hooks-http-timeout` flag:** Allows users to configure a timeout duration for HTTP requests to hook endpoints, preventing indefinite hangs.
- **`-hooks-http-size-limit` flag:** Enables setting a maximum size for HTTP hook response bodies, protecting against potential resource exhaustion from large responses. An error is returned if the limit is exceeded.
- **Content-Type validation:** Ensures that HTTP hook responses have a `Content-Type` of `application/json`.
Furthermore, this PR includes documentation for the newly added `-hooks-http-timeout` and `-hooks-http-size-limit` flags in the HTTP hooks section.
These changes aim to improve the …

hooks: Add timeout and size limit to HTTP hooks and enforce Content-Type

---

cmd/tusd/cli/flags.go
cmd/tusd/cli/serve.go
pkg/handler/concat_test.go
pkg/handler/config.go
pkg/handler/options_test.go
pkg/handler/unrouted_handler.go

Even if the storage supports the [concatenation extension](https://tus.io/protocols/resumable-upload#concatenation), an operator may want to disable support for it.
Partial uploads usually have to be treated slightly different in hooks than normal or final uploads. Applications shouldn't process partial uploads as they are just parts of the entire file. In addition, while normal uploads may be moved immediately after their completion, partial uploads should persist for some time until the client has a chance to concatenation them. If the operator does not want to support these cases, they can disable support for the concatenation extension altogether. For this purpose, a new `-disable-concatenation` flag is introduced.
This PR also fixes a minor bug where the termination extension was …

cli,handler: Add option to disable concatenation extension
