tus/tusd

cmd/tusd/main.go

feat(cmd/tusd): Print the base path

---

.infra/Freyfile.hcl

And fixate `ansible_managed` variable

Make use of ssh pipelining

---

.infra/group_vars/all/_frey.yml

Needed for future role updates and cleanup

Update Frey variables

---

.infra/group_vars/all/_frey.yml

Remove unused dependencies

---

.gitignore

See https://github.com/freyproject/frey/pull/69

Improved .gitignore for Frey using Docker

---

.infra/group_vars/all/_frey.yml

I think this should fix the failing deploy

Fix incorrect install_npm_user

---

s3store/s3store.go
s3store/s3store_test.go

Take IsTruncated field of S3 ListParts API response into account

---

s3store/s3store.go

As noted, one of the comments didn't match the numbers in the code. I fixed a couple of small typos along the way.

Improve comments in s3store

---

unrouted_handler.go

Expose ParseMetadataHeader and SerializeMetadataHeader functions

---

.infra/kube/tusd-kube.yaml

@Acconut We have a secret that contains s3 and reference to it inside the pod.

Switch storage to s3

---

cmd/tusd/cli/composer.go
cmd/tusd/cli/flags.go
cmd/tusd/cli/hooks.go
datastore.go
patch_test.go
unrouted_handler.go
utils_test.go

Fixes https://github.com/tus/tusd/issues/269.

core: Add ability to stop upload from post-receive hook

---

.infra/kube/tusd-kube.yaml
.scripts/deploy_gcloud.sh
.scripts/deploy_kube.sh
.travis.yml
Dockerfile

Polishing the yaml for the deployment as well as updating to different cloud.

Change cloud 

---

pkg/handler/cors_test.go
pkg/handler/unrouted_handler.go

Same as done in https://github.com/tus/tus-node-server/pull/103.
Now committing changes to both unrouted_handler.go and cors_test.go.

Adding Allow `Authorization` Header

---

docs/usage-binary.md

Nothing fancy, just syncing the docs with the command -help usage.

docs: sync binary help.

---

cmd/tusd/cli/hooks/grpc.go

Fix gRPC Hook reference

---

docs/faq.md

Changed `docs/....` to `/docs/....`

Fix link in faq.md

---

docs/faq.md

Added information about CORS to the FAQ.

---

cmd/tusd/cli/flags.go
cmd/tusd/cli/hooks.go
cmd/tusd/cli/hooks/hooks.go
cmd/tusd/cli/hooks/http.go
cmd/tusd/cli/hooks/plugin.go
docs/faq.md
docs/hooks.md
docs/usage-binary.md
pkg/handler/config.go
pkg/handler/unrouted_handler.go

New synchronous hook event `pre-finish` called after an upload is complete but before a response is sent to the client.
Fixes #350

Add pre-finish hook.

---

cmd/tusd/cli/composer.go
cmd/tusd/cli/flags.go
docs/usage-binary.md

This PR address the following issue: https://github.com/tus/tusd/issues/392
But, I'm not sure this is the best way to go about the feature.  Please advise if this should reside behind a feature flag or other ideas.  Thanks.

Enable S3 transfer acceleration

---

.github/workflows/main.yml
Procfile

This PR enables auto deployment of tusd to heroku
wasn't sure what part of the docker/kube build should be removed, so I just left them be for now.

Heroku deployment

---

Dockerfile

The current version contains quite a few vulnerabilities: https://artifacthub.io/packages/helm/sagikazarmark/tusd?modal=security-report

Update alpine version in Dockerfile

---

.gitignore

shall we add an entry to ignore built binary?

ignore tusd binary

---

Procfile

Increase max size to 100GB

---

pkg/azurestore/azureservice.go
pkg/azurestore/azurestore.go

Fix leakage of info when no azure blob is found

---

cmd/tusd/cli/flags.go
cmd/tusd/cli/serve.go
pkg/handler/config.go
pkg/handler/cors_test.go
pkg/handler/handler.go
pkg/handler/unrouted_handler.go

Add a flag to disable downloads of uploaded files

---

cmd/tusd/cli/flags.go
cmd/tusd/cli/serve.go
docs/usage-binary.md
pkg/handler/config.go
pkg/handler/cors_test.go
pkg/handler/unrouted_handler.go

Disable cors headers

---

Dockerfile

Resolves #922 
cc @PatrickMi @jrcichra for testing

fix(docker): correct multi platform build

---

.github/workflows/release.yaml
Dockerfile
go.mod
go.sum

Combining multiple dependencies PRs into one.
<details>
<summary>Instructions for merging</summary>
* **Use a merge commit**, so that GitHub will mark all original PRs as merged.
* If your repository does not have merge commits enabled, please temporarily enable them in settings. Tick `Allow merge commits` in the repository settings.
* When ready, merge this PR using `Create a merge commit`.
</details>
* build(deps): bump docker/login-action from 2.1.0 to 2.2.0 (#974) @app/dependabot
* build(deps): bump docker/setup-buildx-action from 2.5.0 to 2.8.0 (#973) @app/dependabot
* build(deps): bump docker/metadata-action from 4.4.0 to 4.6.0 (#972) @app/dependabot
* build(deps): bump golang from 1.20.4-alpine to 1.20.5-alpine (#971) @app/dependabot
* build(deps): bump alpine from 3.18.0 to 3.18.2 …

Combined dependencies PR

---

cmd/tusd/cli/flags.go
cmd/tusd/cli/serve.go
pkg/handler/config.go
pkg/handler/cors_test.go
pkg/handler/unrouted_handler.go
pkg/handler/utils_test.go

follow up of https://github.com/tus/tusd/pull/942

feat: Add flag to control CORS Origin header

---

Dockerfile

Fixes https://github.com/tus/tusd/issues/1045.

docker: Fix version embedding in tusd

---

cmd/tusd/cli/hooks.go
pkg/hooks/plugin/plugin.go

cli: Adjust logging format from plugin hooks to CLI's format

---

examples/hooks/plugin/hook_handler.go

Correct comment in hook example

examples: Correct hook type in plugin example

---

docs/_storage-backends/aws-s3.md
docs/_storage-backends/azure-blob-storage.md
docs/minio.txt

Closes https://github.com/tus/tusd/issues/1094.

  docs: Add example usage with Minio and Azurite
